FROM bellsoft/liberica-openjdk-alpine:latest
COPY ./java ./src
RUN mkdir ./out
RUN javac -sourcepath ./src -d out src/java_core/lesson1/sample/Main.java
CMD java -classpath ./out java_core.lesson1.sample.Main